### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by kleenkanteen** [devottys/cittyscape#2]
Could I get a demo vid? Easy to upload on streamable.com.

**Comment by saulpw** [comment]
Hey @kleenkanteen!  I'm in the middle of a big refactor, but once that's working, I'll upload a video either on streamable or youtube or elsewhere.  At the moment though it's just like the screenshot, except it scrolls through randomly generated buildings :)  Are you interested in playing with it yourself, or just curious what it looks like?

**Comment by kleenkanteen** [comment]
I'm curious to see what it looks like, and if interesting enough, to spin up a docker container and play around with it
